"""Add resource booking models

Revision ID: 1148f2b11440
Revises: ad5e80a601eb
Create Date: 2026-07-12 10:12:02.305901

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1148f2b11440'
down_revision = 'ad5e80a601eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookable_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('is_bookable', sa.Boolean(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name='fk_bookable_resource_asset', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id')
    )
    op.create_index(op.f('ix_bookable_resources_id'), 'bookable_resources', ['id'], unique=False)
    op.create_table('resource_bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('UPCOMING', 'ONGOING', 'COMPLETED', 'CANCELLED', name='bookingstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['bookable_resources.id'], name='fk_resource_booking_resource', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_resource_booking_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_bookings_id'), 'resource_bookings', ['id'], unique=False)
    op.create_index(op.f('ix_resource_bookings_status'), 'resource_bookings', ['status'], unique=False)
    op.create_table('booking_activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('action_by', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.Enum('CREATED', 'RESCHEDULED', 'CANCELLED', name='bookingaction'), nullable=False),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['action_by'], ['users.id'], name='fk_booking_activity_log_user', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['booking_id'], ['resource_bookings.id'], name='fk_booking_activity_log_booking', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_activity_logs_id'), 'booking_activity_logs', ['id'], unique=False)
    op.create_table('booking_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('original_start_time', sa.DateTime(), nullable=False),
    sa.Column('original_end_time', sa.DateTime(), nullable=False),
    sa.Column('final_status', sa.String(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['resource_bookings.id'], name='fk_booking_history_booking', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_history_id'), 'booking_history', ['id'], unique=False)
    op.create_table('booking_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('notification_type', sa.Enum('REMINDER', 'CONFLICT', 'CANCELLED', 'CREATED', 'RESCHEDULED', name='notificationtype'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['resource_bookings.id'], name='fk_booking_notification_booking', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_booking_notification_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_notifications_id'), 'booking_notifications', ['id'], unique=False)
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.drop_table('bookings')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_booking_asset')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_booking_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('bookings_pkey'))
    )
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.drop_index(op.f('ix_booking_notifications_id'), table_name='booking_notifications')
    op.drop_table('booking_notifications')
    op.drop_index(op.f('ix_booking_history_id'), table_name='booking_history')
    op.drop_table('booking_history')
    op.drop_index(op.f('ix_booking_activity_logs_id'), table_name='booking_activity_logs')
    op.drop_table('booking_activity_logs')
    op.drop_index(op.f('ix_resource_bookings_status'), table_name='resource_bookings')
    op.drop_index(op.f('ix_resource_bookings_id'), table_name='resource_bookings')
    op.drop_table('resource_bookings')
    op.drop_index(op.f('ix_bookable_resources_id'), table_name='bookable_resources')
    op.drop_table('bookable_resources')
    # ### end Alembic commands ###
