"""extend_models_for_screens_3_4_5

Revision ID: 51a24d088125
Revises: ad5e80a601eb
Create Date: 2026-07-12 14:59:14.834658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51a24d088125'
down_revision = 'ad5e80a601eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('planned', 'active', 'completed', 'closed', name='auditcyclestatus'), nullable=False),
    sa.Column('auditor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['auditor_id'], ['users.id'], name='fk_audit_cycle_auditor'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_cycles_id'), 'audit_cycles', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_notification_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('audit_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'verified', 'missing', 'damaged', name='audititemstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name='fk_audit_item_asset', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cycle_id'], ['audit_cycles.id'], name='fk_audit_item_cycle', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_items_id'), 'audit_items', ['id'], unique=False)
    op.add_column('allocations', sa.Column('employee_id', sa.Integer(), nullable=True))
    op.add_column('allocations', sa.Column('department_id', sa.Integer(), nullable=True))
    op.add_column('allocations', sa.Column('expected_return', sa.DateTime(), nullable=True))
    op.add_column('allocations', sa.Column('return_notes', sa.Text(), nullable=True))
    op.add_column('allocations', sa.Column('condition_on_return', sa.String(), nullable=True))
    op.create_foreign_key('fk_allocation_employee', 'allocations', 'users', ['employee_id'], ['id'])
    op.create_foreign_key('fk_allocation_department', 'allocations', 'departments', ['department_id'], ['id'])
    op.add_column('assets', sa.Column('condition', sa.Enum('NEW', 'GOOD', 'FAIR', 'DAMAGED', 'SCRAP', name='assetcondition'), nullable=False))
    op.add_column('assets', sa.Column('location', sa.String(), nullable=True))
    op.add_column('assets', sa.Column('purchase_cost', sa.Float(), nullable=True))
    op.add_column('assets', sa.Column('photo_url', sa.String(), nullable=True))
    op.add_column('assets', sa.Column('document_url', sa.String(), nullable=True))
    op.add_column('assets', sa.Column('is_bookable', sa.Boolean(), nullable=False))
    op.add_column('assets', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('assets', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('assets', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('assets', 'asset_tag',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key('fk_asset_creator', 'assets', 'users', ['created_by_id'], ['id'])
    op.add_column('categories', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('categories', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('departments', sa.Column('description', sa.String(), nullable=True))
    op.add_column('departments', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('departments', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('transfer_requests', sa.Column('asset_id', sa.Integer(), nullable=True))
    op.add_column('transfer_requests', sa.Column('current_holder', sa.Integer(), nullable=True))
    op.add_column('transfer_requests', sa.Column('requested_holder', sa.Integer(), nullable=True))
    op.add_column('transfer_requests', sa.Column('requested_by', sa.Integer(), nullable=True))
    op.add_column('transfer_requests', sa.Column('approved_by', sa.Integer(), nullable=True))
    op.add_column('transfer_requests', sa.Column('reason', sa.String(), nullable=True))
    op.add_column('transfer_requests', sa.Column('requested_at', sa.DateTime(), nullable=True))
    op.add_column('transfer_requests', sa.Column('approved_at', sa.DateTime(), nullable=True))
    op.alter_column('transfer_requests', 'status',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('pending', 'requested', 'approved', 'rejected', 'cancelled', name='transferrequeststatus'),
               existing_nullable=False)
    op.create_foreign_key('fk_transfer_approver', 'transfer_requests', 'users', ['approved_by'], ['id'])
    op.create_foreign_key('fk_transfer_asset', 'transfer_requests', 'assets', ['asset_id'], ['id'])
    op.create_foreign_key('fk_transfer_requested_holder', 'transfer_requests', 'users', ['requested_holder'], ['id'])
    op.create_foreign_key('fk_transfer_requester', 'transfer_requests', 'users', ['requested_by'], ['id'])
    op.create_foreign_key('fk_transfer_current_holder', 'transfer_requests', 'users', ['current_holder'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_transfer_current_holder', 'transfer_requests', type_='foreignkey')
    op.drop_constraint('fk_transfer_requester', 'transfer_requests', type_='foreignkey')
    op.drop_constraint('fk_transfer_requested_holder', 'transfer_requests', type_='foreignkey')
    op.drop_constraint('fk_transfer_asset', 'transfer_requests', type_='foreignkey')
    op.drop_constraint('fk_transfer_approver', 'transfer_requests', type_='foreignkey')
    op.alter_column('transfer_requests', 'status',
               existing_type=sa.Enum('pending', 'requested', 'approved', 'rejected', 'cancelled', name='transferrequeststatus'),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
    op.drop_column('transfer_requests', 'approved_at')
    op.drop_column('transfer_requests', 'requested_at')
    op.drop_column('transfer_requests', 'reason')
    op.drop_column('transfer_requests', 'approved_by')
    op.drop_column('transfer_requests', 'requested_by')
    op.drop_column('transfer_requests', 'requested_holder')
    op.drop_column('transfer_requests', 'current_holder')
    op.drop_column('transfer_requests', 'asset_id')
    op.drop_column('departments', 'updated_at')
    op.drop_column('departments', 'created_at')
    op.drop_column('departments', 'description')
    op.drop_column('categories', 'updated_at')
    op.drop_column('categories', 'created_at')
    op.drop_constraint('fk_asset_creator', 'assets', type_='foreignkey')
    op.alter_column('assets', 'asset_tag',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('assets', 'updated_at')
    op.drop_column('assets', 'created_at')
    op.drop_column('assets', 'created_by_id')
    op.drop_column('assets', 'is_bookable')
    op.drop_column('assets', 'document_url')
    op.drop_column('assets', 'photo_url')
    op.drop_column('assets', 'purchase_cost')
    op.drop_column('assets', 'location')
    op.drop_column('assets', 'condition')
    op.drop_constraint('fk_allocation_department', 'allocations', type_='foreignkey')
    op.drop_constraint('fk_allocation_employee', 'allocations', type_='foreignkey')
    op.drop_column('allocations', 'condition_on_return')
    op.drop_column('allocations', 'return_notes')
    op.drop_column('allocations', 'expected_return')
    op.drop_column('allocations', 'department_id')
    op.drop_column('allocations', 'employee_id')
    op.drop_index(op.f('ix_audit_items_id'), table_name='audit_items')
    op.drop_table('audit_items')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_audit_cycles_id'), table_name='audit_cycles')
    op.drop_table('audit_cycles')
    # ### end Alembic commands ###
