"""Add purchase_date to Asset

Revision ID: ad5e80a601eb
Revises: 82d15df66ef5
Create Date: 2026-07-12 08:02:34.615087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad5e80a601eb'
down_revision = '82d15df66ef5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('purchase_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'purchase_date')
    # ### end Alembic commands ###
